config/routes.rb
Rails.application.routes.draw do
#For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'

  # As a user, I can list tasks

  get 'list', to: 'tasks#list', as: 'list'

  # As a user, I can add a new task
  get 'tasks/new', to: 'tasks#new', as: 'new'
  post 'tasks', to: 'tasks#create'

  # As a user, I can view the details of a task
  get 'tasks/:id', to: 'tasks#show', as: 'task'

  # As a user, I can edit a task
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  patch 'tasks/:id', to: 'tasks#update'

  # As a user, I can remove a task

  delete 'tasks/:id', to: 'tasks#destroy', as: 'delete'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
  end

  def list
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>

  <%= t.label :details %>
  <%= t.text_field :details %>

  <%= t.check_box :completed, {}, "true", "false" %>

  <%= t.submit %>
<% end %>

<%= link_to 'Back to main page', tasks_path %>

app/views/tasks/index.html.erb
<h1>Hello there!</h1>

<ul>
  <li><%= link_to 'List all tasks', list_path %></li>
  <li><%= link_to 'Add a new task', new_path %></li>
</ul>

app/views/tasks/list.html.erb
<h1>Here is your list of tasks</h1>
<h3>Click on the one you want to see in detail</h3>
<% @tasks.each do |task| %>
  <p><%= link_to task.title, task_path(task.id) %>  <%= link_to 'EDIT', edit_path(task.id) %>  <%= link_to 'DELETE', delete_path(task), method: :delete %></p>
<% end %>

<%= link_to 'Back to main page', tasks_path %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>

  <%= t.label :details %>
  <%= t.text_field :details %>

  <%= t.check_box :completed, {}, "true", "false" %>

  <%= t.submit %>
<% end %>

<%= link_to 'Back to main page', tasks_path %>

app/views/tasks/show.html.erb
<h1>Here you go:</h1>
  <h2>Title: <%= @task.title %></h2>
  <h2>Details: <%= @task.details %></h2>
  <h2>Completed: <%= @task.completed %></h2>

<%= link_to 'Back to main page', tasks_path %>